### ISSUE TITLE
Add --alias option to handle memory region aliases not exposed by .elf

### ISSUE THREAD

**Issue by swordligit** [adamgreen/CrashDebug#6] opened 2019-06-03 09:59 UTC
When I use "--bin" like the following command to start gdb
```
arm-none-eabi-gdb mytest.elf -ex "set target-charset ASCII" -ex "target remote | ./CrashDebug --bin mytest.bin 0xc000000  --dump crash.txt"
```
it generate the full call back trace with the command "bt";
But if I use "--elf" like this,
```
arm-none-eabi-gdb mytest.elf -ex "set target-charset ASCII" -ex "target remote | ./CrashDebug --elf mytest.elf  --dump crash.txt"
```
it only show the two level call stack(the call stack is also right with these two level);

For the case with "--bin", when I input "info mem"
it shows only the task's stack, and no global data area, like this
```
(gdb) info mem
Using memory regions provided by the target.
Num Enb Low Addr   High Addr  Attrs 
0   y  	0x0c000000 0x0c0d2698 flash blocksize 0x1 nocache 
1   y  	0x200131bc 0x200145bc rw nocache --task A's stack
2   y  	0x2001e29c 0x2001fa9c rw nocache  --task B's stack 
3   y  	0x20020128 0x20020928 rw nocache --task C's stack 
4   y  	0x20024268 0x20024668 rw nocache  --task D's stack 
5   y  	0x20024c28 0x20025428 rw nocache  --task E's stack
6   y  	0x200a9300 0x200a9800 rw nocache  --task F's stack 
7   y  	0xe000ed28 0xe000ed3c rw nocache
```
For the case "--elf", it shows different memory info
```
(gdb) info mem
Using memory regions provided by the target.
Num Enb Low Addr   High Addr  Attrs 
0   y  	0x200131bc 0x200145bc rw nocache 
1   y  	0x2001e29c 0x2001fa9c rw nocache 
2   y  	0x20020128 0x20020928 rw nocache 
3   y  	0x20024268 0x20024668 rw nocache 
4   y  	0x20024c28 0x20025428 rw nocache 
5   y  	0x200a9300 0x200a9800 rw nocache 
6   y  	0x3c000000 0x3c000010 flash blocksize 0x1 nocache 
7   y  	0x3c000010 0x3c000c58 flash blocksize 0x1 nocache 
8   y  	0x3c000c58 0x3c002dc0 flash blocksize 0x1 nocache 
9   y  	0x3c002dc0 0x3c0031e4 flash blocksize 0x1 nocache 
10  y  	0x3c0031e4 0x3c003810 flash blocksize 0x1 nocache 
11  y  	0x3c003810 0x3c003cf8 flash blocksize 0x1 nocache 
12  y  	0x3c003cf8 0x3c006250 flash blocksize 0x1 nocache 
13  y  	0x3c006250 0x3c00ad70 flash blocksize 0x1 nocache 
14  y  	0x3c00ad70 0x3c00af00 flash blocksize 0x1 nocache 
15  y  	0x3c00af00 0x3c00af04 flash blocksize 0x1 nocache 
16  y  	0x3c00af04 0x3c00af08 flash blocksize 0x1 nocache 
17  y  	0x3c00af08 0x3c011eb8 flash blocksize 0x1 nocache 
18  y  	0x3c011eb8 0x3c011ebc flash blocksize 0x1 nocache 
19  y  	0x3c011ebc 0x3c011ec0 flash blocksize 0x1 nocache 
20  y  	0x3c011ec0 0x3c011ec4 flash blocksize 0x1 nocache 
21  y  	0x3c011ec4 0x3c011ec8 flash blocksize 0x1 nocache 
22  y  	0x3c011ec8 0x3c013d0c flash blocksize 0x1 nocache 
23  y  	0x3c013d0c 0x3c013d10 flash blocksize 0x1 nocache 
24  y  	0x3c013d10 0x3c013d14 flash blocksize 0x1 nocache 
25  y  	0x3c013d14 0x3c013d18 flash blocksize 0x1 nocache 
26  y  	0x3c013d18 0x3c014a0c flash blocksize 0x1 nocache 
27  y  	0x3c014a0c 0x3c014a10 flash blocksize 0x1 nocache 
28  y  	0x3c014a10 0x3c014a14 flash blocksize 0x1 nocache 
29  y  	0x3c014a14 0x3c014a18 flash blocksize 0x1 nocache 
30  y  	0x3c014a18 0x3c014a1c flash blocksize 0x1 nocache 
31  y  	0x3c014a1c 0x3c07c7a0 flash blocksize 0x1 nocache 
32  y  	0x3c07c7a0 0x3c0d1b08 flash blocksize 0x1 nocache 
33  y  	0x3c0d1b08 0x3c0d2590 flash blocksize 0x1 nocache 
34  y  	0x3c0d2590 0x3c0d2698 flash blocksize 0x1 nocache 
35  y  	0xe000ed28 0xe000ed3c rw nocache
```

Some more info, arm-none-eabi-readelf -S mytest.elf
```
There are 68 section headers, starting at offset 0x803098:

Section Headers:
  [Nr] Name              Type            Addr     Off    Size   ES Flg Lk Inf Al
  [ 0]                   NULL            00000000 000000 000000 00      0   0  0
  [ 1] .boot_struct      PROGBITS        3c000000 010000 000010 00   A  0   0  4
  [ 2] .boot_text_flash  PROGBITS        0c000010 010010 000c48 00  AX  0   0  8
  [ 3] .got_info         PROGBITS        3c000c58 020c58 000000 00  WA  0   0  4
  [ 4] .vector_table     NOBITS          20000000 010000 000100 00  WA  0   0  4
  [ 5] .reboot_param     NOBITS          20000100 010000 000040 00  WA  0   0  4
  [ 6] .userdata_pool    NOBITS          20000140 010000 001000 00  WA  0   0  4
  [ 7] .boot_text_sram   PROGBITS        00201140 011140 002168 00  AX  0   0  8
  [ 8] .boot_data_sram   PROGBITS        200032a8 0232a8 000424 00  WA  0   0  4
  [ 9] .boot_bss_sram    NOBITS          200036cc 0336cc 004420 00  WA  0   0  4
  [10] .sram_text        PROGBITS        00207aec 027aec 00062c 00  AX  0   0  8
  [11] .sram_data        PROGBITS        20008118 028118 0004e8 00  WA  0   0  4
  [12] .sram_bss         NOBITS          20008600 038600 000008 00  WA  0   0  1
  [13] .fast_text_sram   PROGBITS        002aa000 02a000 002558 00  AX  0   0  8
  [14] .overlay_text0    PROGBITS        002ac558 02c558 004b20 00  AX  0   0  8
  [15] .overlay_text1    PROGBITS        002ac558 03c558 000190 00  AX  0   0  8
  [16] .overlay_text2    PROGBITS        002ac558 04c558 000004 00  WA  0   0  1
  [17] .overlay_text3    PROGBITS        002ac558 05c558 000004 00  WA  0   0  1
  [18] .overlay_text4    PROGBITS        002ac558 06c558 006fb0 00  AX  0   0  8
  [19] .overlay_text5    PROGBITS        002ac558 07c558 000004 00  WA  0   0  1
  [20] .overlay_text6    PROGBITS        002ac558 08c558 000004 00  WA  0   0  1
  [21] .overlay_text7    PROGBITS        002ac558 09c558 000004 00  WA  0   0  1
  [22] .overlay_text_end PROGBITS        002ac558 0ac558 000004 00  WA  0   0  1
  [23] .overlay_data0    PROGBITS        20008608 0b8608 001e44 00  WA  0   0  4
  [24] .overlay_data1    PROGBITS        20008608 0c8608 000004 00  WA  0   0  1
  [25] .overlay_data2    PROGBITS        20008608 0d8608 000004 00  WA  0   0  1
  [26] .overlay_data3    PROGBITS        20008608 0e8608 000004 00  WA  0   0  1
  [27] .overlay_data4    PROGBITS        20008608 0f8608 000cf4 00   A  0   0  4
  [28] .overlay_data5    PROGBITS        20008608 108608 000004 00  WA  0   0  1
  [29] .overlay_data6    PROGBITS        20008608 118608 000004 00  WA  0   0  1
  [30] .overlay_data7    PROGBITS        20008608 128608 000004 00  WA  0   0  1
  [31] .overlay_data_end PROGBITS        20008608 138608 000004 00  WA  0   0  1
  [32] .text             PROGBITS        0c014a1c 144a1c 067d7c 00  AX  0   0 16
  [33] .ARM.exidx        ARM_EXIDX       0c07c798 1ac798 000008 00  AL 32   0  4
  [34] .rodata           PROGBITS        3c07c7a0 1ac7a0 055368 00   A  0   0  8
  [35] .ai.gatt.server.t PROGBITS        3c0d1b08 212698 000000 00   W  0   0  1
  [36] .ai.ble.handler.t PROGBITS        3c0d1b08 212698 000000 00   W  0   0  1
  [37] .ai.spp.register. PROGBITS        3c0d1b08 212698 000000 00   W  0   0  1
  [38] .tota.cmd.table   PROGBITS        3c0d1b08 212698 000000 00   W  0   0  1
  [39] .ai.handler.funct PROGBITS        3c0d1b08 212698 000000 00   W  0   0  1
  [40] .custom.cmd.table PROGBITS        3c0d1b08 212698 000000 00   W  0   0  1
  [41] .thirdparty.event PROGBITS        3c0d1b08 212698 000000 00   W  0   0  1
  [42] .data             PROGBITS        2000a44c 20a44c 000a88 00  WA  0   0  4
  [43] .bss              NOBITS          2000aed4 20aed4 01aacc 00  WA  0   0 256
  [44] .heap             NOBITS          200259a0 2159a0 001000 00  WA  0   0  1
  [45] .stack_dummy      PROGBITS        200269a0 212698 000d00 00   W  0   0  1
  [46] .system_info      PROGBITS        3c0d2590 213398 000000 00   W  0   0  1
  [47] .build_info       PROGBITS        3c0d2590 212590 000100 00   A  0   0  4
  [48] .code_start_addr  PROGBITS        3c0d2690 212690 000008 00  WA  0   0  1
  [49] .custom_parameter NOBITS          3c3fd000 21d000 001000 00  WA  0   0  1
  [50] .userdata         NOBITS          3c3fe000 21d000 001000 00  WA  0   0  1
  [51] .factory          NOBITS          3c3ff000 21d000 001000 00  WA  0   0  1
  [52] .ARM.attributes   ARM_ATTRIBUTES  00000000 213398 000030 00      0   0  1
  [53] .comment          PROGBITS        00000000 2133c8 00007f 01  MS  0   0  1
  [54] .svc_table        PROGBITS        00000000 213447 000004 00      0   0  1
  [55] .debug_info       PROGBITS        00000000 21344b 3496cc 00      0   0  1
  [56] .debug_abbrev     PROGBITS        00000000 55cb17 047d6b 00      0   0  1
  [57] .debug_loc        PROGBITS        00000000 5a4882 0e0f5f 00      0   0  1
  [58] .debug_aranges    PROGBITS        00000000 6857e1 00abc8 00      0   0  1
  [59] .debug_ranges     PROGBITS        00000000 6903a9 020a50 00      0   0  1
  [60] .debug_line       PROGBITS        00000000 6b0df9 07490c 00      0   0  1
  [61] .debug_str        PROGBITS        00000000 725705 05c65f 01  MS  0   0  1
  [62] .debug_frame      PROGBITS        00000000 781d64 024cd4 00      0   0  4
  [63] .stab             PROGBITS        00000000 7a6a38 0000cc 0c     64   0  4
  [64] .stabstr          STRTAB          00000000 7a6b04 0001ed 00      0   0  1
  [65] .symtab           SYMTAB          00000000 7a6cf4 03b010 10     66 11530  4
  [66] .strtab           STRTAB          00000000 7e1d04 020ffa 00      0   0  1
  [67] .shstrtab         STRTAB          00000000 802cfe 000398 00      0   0  1
```

**Comment by adamgreen** [comment] 2019-06-03 17:52
It looks like the .elf loads up a bunch of segments that maybe you don't need and then skips the one at 0x0c000000 that you do. CrashDebug uses the program headers and not the section headers to determine what it should load as flash. Can you dump those instead (using the **-l** command line flag instead of **-S**)? It might be helpful to see your linker script as well to see if it is doing something that would cause one segment to not be marked as expected.

**Comment by swordligit** [comment] 2019-06-04 03:32
This is the result of  realdelf -l
```
arm-none-eabi-readelf -l out/best2300_ep/best2300_ep.elf 

Elf file type is EXEC (Executable file)
Entry point 0xc000011
There are 36 program headers, starting at offset 52

Program Headers:
  Type           Offset   VirtAddr   PhysAddr   FileSiz MemSiz  Flg Align
  EXIDX          0x1ac798 0x0c07c798 0x3c07c798 0x00008 0x00008 R   0x4
  LOAD           0x010000 0x20000000 0x20000000 0x00000 0x01140 RW  0x10000
  LOAD           0x010000 0x3c000000 0x3c000000 0x00010 0x00010 R   0x10000
  LOAD           0x010010 0x0c000010 0x3c000010 0x00c48 0x00c48 R E 0x10000
  LOAD           0x011140 0x00201140 0x3c000c58 0x02168 0x02168 R E 0x10000
  LOAD           0x020c58 0x3c000c58 0x3c000c58 0x00000 0x00000 RW  0x10000
  LOAD           0x0232a8 0x200032a8 0x3c002dc0 0x00424 0x00424 RW  0x10000
  LOAD           0x027aec 0x00207aec 0x3c0031e4 0x0062c 0x0062c R E 0x10000
  LOAD           0x0336cc 0x200036cc 0x3c0031e4 0x00000 0x04420 RW  0x10000
  LOAD           0x028118 0x20008118 0x3c003810 0x004e8 0x004e8 RW  0x10000
  LOAD           0x02a000 0x002aa000 0x3c003cf8 0x02558 0x02558 R E 0x10000
  LOAD           0x038600 0x20008600 0x3c003cf8 0x00000 0x00008 RW  0x10000
  LOAD           0x02c558 0x002ac558 0x3c006250 0x04b20 0x04b20 R E 0x10000
  LOAD           0x03c558 0x002ac558 0x3c00ad70 0x00190 0x00190 R E 0x10000
  LOAD           0x04c558 0x002ac558 0x3c00af00 0x00004 0x00004 RW  0x10000
  LOAD           0x05c558 0x002ac558 0x3c00af04 0x00004 0x00004 RW  0x10000
  LOAD           0x06c558 0x002ac558 0x3c00af08 0x06fb0 0x06fb0 R E 0x10000
  LOAD           0x07c558 0x002ac558 0x3c011eb8 0x00004 0x00004 RW  0x10000
  LOAD           0x08c558 0x002ac558 0x3c011ebc 0x00004 0x00004 RW  0x10000
  LOAD           0x09c558 0x002ac558 0x3c011ec0 0x00004 0x00004 RW  0x10000
  LOAD           0x0ac558 0x002ac558 0x3c011ec4 0x00004 0x00004 RW  0x10000
  LOAD           0x0b8608 0x20008608 0x3c011ec8 0x01e44 0x01e44 RW  0x10000
  LOAD           0x0c8608 0x20008608 0x3c013d0c 0x00004 0x00004 RW  0x10000
  LOAD           0x0d8608 0x20008608 0x3c013d10 0x00004 0x00004 RW  0x10000
  LOAD           0x0e8608 0x20008608 0x3c013d14 0x00004 0x00004 RW  0x10000
  LOAD           0x0f8608 0x20008608 0x3c013d18 0x00cf4 0x00cf4 R   0x10000
  LOAD           0x108608 0x20008608 0x3c014a0c 0x00004 0x00004 RW  0x10000
  LOAD           0x118608 0x20008608 0x3c014a10 0x00004 0x00004 RW  0x10000
  LOAD           0x128608 0x20008608 0x3c014a14 0x00004 0x00004 RW  0x10000
  LOAD           0x138608 0x20008608 0x3c014a18 0x00004 0x00004 RW  0x10000
  LOAD           0x144a1c 0x0c014a1c 0x3c014a1c 0x67d84 0x67d84 R E 0x10000
  LOAD           0x1ac7a0 0x3c07c7a0 0x3c07c7a0 0x55368 0x55368 R   0x10000
  LOAD           0x20a44c 0x2000a44c 0x3c0d1b08 0x00a88 0x1b554 RW  0x10000
  LOAD           0x212590 0x3c0d2590 0x3c0d2590 0x00108 0x00108 RW  0x10000
  LOAD           0x2159a0 0x200259a0 0x3c0ed05c 0x00000 0x01000 RW  0x10000
  LOAD           0x21d000 0x3c3fd000 0x3c3fd000 0x00000 0x03000 RW  0x10000

 Section to Segment mapping:
  Segment Sections...
   00     .ARM.exidx 
   01     .vector_table .reboot_param .userdata_pool 
   02     .boot_struct 
   03     .boot_text_flash 
   04     .boot_text_sram 
   05     .got_info 
   06     .boot_data_sram 
   07     .sram_text 
   08     .boot_bss_sram 
   09     .sram_data 
   10     .fast_text_sram 
   11     .sram_bss 
   12     .overlay_text0 
   13     .overlay_text1 
   14     .overlay_text2 
   15     .overlay_text3 
   16     .overlay_text4 
   17     .overlay_text5 
   18     .overlay_text6 
   19     .overlay_text7 
   20     .overlay_text_end 
   21     .overlay_data0 
   22     .overlay_data1 
   23     .overlay_data2 
   24     .overlay_data3 
   25     .overlay_data4 
   26     .overlay_data5 
   27     .overlay_data6 
   28     .overlay_data7 
   29     .overlay_data_end 
   30     .text .ARM.exidx 
   31     .rodata 
   32     .data .bss 
   33     .build_info .code_start_addr 
   34     .heap 
   35     .custom_parameter .userdata .factory 
```
my link file has a lot of macros from other files, and is not
so readable, if needed, I will modify it with more readable
format.

**Comment by adamgreen** [comment] 2019-06-04 04:34
> my link file has a lot of macros from other files, and is not so readable, if needed, I will modify it with more readable format.

**Comment by swordligit** [comment] 2019-06-04 04:44
One more point， I am not sure if it helps.
my hardware has a features that 
0x3c000000 is alias with 0x0c000000
,which means these two address are the same
hardware address. and this is mainly for CODE.
0x20000000 is alias with 0x200000,
which mainly used for RAM, but our overlay code
is locate in this area for acceleration.

**Comment by adamgreen** [comment] 2019-06-04 04:46
> my link file has a lot of macros from other files, and is not so readable, if needed, I will modify it with more readable format.

I think we can start with what you have already sent me then.

Thanks for sending me the program header dump. It does look like CrashDebug is loading the sections that I expect but there appears to be a discrepancy between what you loaded manually with the **--bin** option and what CrashDebug loads with its **--elf** handling.

I see that you manually loaded flash data at address **0x0c000000**
```-ex "target remote | ./CrashDebug --bin mytest.bin 0xc000000  --dump crash.txt"```
but the ELF seems to indicate that it should be placed at **0x3c000010**
```
Program Headers:
  Type           Offset   VirtAddr   PhysAddr   FileSiz MemSiz  Flg Align
...
  LOAD           0x010010 0x0c000010 0x3c000010 0x00c48 0x00c48 R E 0x10000
```

Do you know what causes this discrepancy? Based on what I see in the ELF, it looks like the FLASH for your device is at around 0x3c000000 and 0x0c000000 is a RAM location that the code gets copied into at runtime.

**Comment by adamgreen** [comment] 2019-06-04 04:56
> 0x3c000000 is alias with 0x0c000000,which means these two address are the same hardware address. and this is mainly for CODE. 0x20000000 is alias with 0x200000,...

CrashDebug doesn't have the ability to do this type of aliasing. I guess it could be added but it would be a pain for the user as they would have to specify the aliasing ranges on the command line. It can't be easily gleaned from the ELF headers themselves.

The only current workaround is for you to dump the aliased regions (the ones not automatically picked up by CrashDeby from the ELF headers) as though they were RAM.

**Comment by swordligit** [comment] 2019-06-04 05:12
Ok, will do a test, will let you know the result, thanks a lot.

**Comment by adamgreen** [comment] 2019-06-04 05:39
> Ok, will do a test, will let you know the result, thanks a lot.

Sounds like a plan!

**Comment by swordligit** [comment] 2019-06-04 07:39
But I am still confused, why I cannot just use --elf(and not --bin),
because I think elf already has every detailed info, even the 0x3c000000 is
alias with 0x0c000000, there are still info that physical address  points to
0x3c000000, and virtual address points to 0x0c000000.

**Comment by adamgreen** [comment] 2019-06-04 08:09
But that isn't the only scenario where the ELF will give differing virtual and physical addresses. It also happens when the linker knows that code/data will be loaded into FLASH initially and then copied into RAM later. That is a very common scenario for .data sections. It isn't an aliasing operation there, it is the result of a copy that occurs at reset. 

A possible solution:
* Have CrashDebug run through the program headers and do exactly every load operation that it indicates:
  * Treat as FLASH if section is read-only and load data in from .elf. These are the only regions currently loaded as it expects RAM to come from dump.
  * Treat as RAM if read/write. Pre-load data from .elf into designated RAM locations. Doesn't do this today.
  * Zero fill any sections which aren't fully backed by .elf contents. No longer does this today.
  * Perform above operations for both the physical and virtual addresses. Doesn't do this today.
* Attempt to write the contents of the crash dump to simulated RAM and create a new region if it doesn't already exist from the .elf load. This means that any data that was preloaded from the .elf can be overwritten by more current data from the dump.

This would cover your aliased read-only sections but not the aliased read/write sections. Those would still need to be dumped twice into the crash dump, once for each address alias.

There is a reason I don't do it this way currently though. If a user doesn't dump the more recent contents of something like the .data or .bss section in their crash dump then they will see the reset values in GDB instead of the invalid address error that they currently get and I think the error is more appropriate.

**Comment by swordligit** [comment] 2019-06-04 10:11
> The only current workaround is for you to dump the aliased regions (the ones not automatically picked up by CrashDeby from the ELF headers) as though they were RAM.

you are right, I dump the address 0x0c000000 to 0x0c0c8000(about 800K bytes),
now it can dump all of the call stack, thanks a lot.
but dump all the text section is a bit painful.

**Comment by swordligit** [comment] 2019-06-04 12:38
After I added some dump region,  the gdb "info mem"
always return
```
(gdb) info mem
Using memory regions provided by the target.
There are no memory regions defined.
```
what I added is the data area and bss area
```
const CrashCatcherMemoryRegion* CrashCatcher_GetMemoryRegions(void)
{
    static CrashCatcherMemoryRegion regions[OS_TASK_CNT + 1 + 1 + 1 + 1 ];
    int i=0;
    int j=0;
    for (i = 0; i < os_maxtaskrun; i++) {
        if (os_active_TCB[i]) {
            regions[j].startAddress = (uint32_t)(((P_TCB)os_active_TCB[i]))->stack;//priv_stack;
            regions[j].endAddress = (uint32_t)((P_TCB)os_active_TCB[i])->stack + ((P_TCB)os_active_TCB[i])->priv_stack;
            regions[j++].elementSize = CRASH_CATCHER_BYTE;
        }
    }

    regions[j].startAddress = (uint32_t)&__data_start__;
    regions[j].endAddress = (uint32_t)&__data_end__;
    regions[j].elementSize = CRASH_CATCHER_BYTE;
    j++;

    regions[j].startAddress = (uint32_t)&__bss_start__;
    regions[j].endAddress = (uint32_t)&__bss_end__;
    regions[j].elementSize = CRASH_CATCHER_BYTE;
    j++;

    regions[j].startAddress = 0x0c000000;
    regions[j].endAddress =   0x0c0c8000;
    regions[j].elementSize = CRASH_CATCHER_BYTE;
    j++;

    regions[j].startAddress = 0xFFFFFFFF;
    regions[j].endAddress = 0xFFFFFFFF;
    regions[j].elementSize = CRASH_CATCHER_BYTE;
    return regions;

```
add __data_start__ and __data_end__ come from link script.

But I think I can dump the global data and static data rightly use
the gdb print command.

**Comment by adamgreen** [comment] 2019-06-04 19:51
What microcontroller are you using which has these aliases and why does it have them? Do they need to be used?

**Comment by swordligit** [comment] 2019-06-05 03:13
It's our own chip with the cortex M4 core.
The reason for alias I think one benefit is one space can be
used both as SRAM and CODE , if used for the CODE, cpu can 
access this space by lower address, if  as SRAM,
by higher address, so CPU will do some optimization.
```
The Code, SRAM, and external RAM regions can hold programs. However, ARM recommends that 
programs always use the Code region. This is because the processor has separate buses that enable 
instruction fetches and data accesses to occur simultaneously.

```
https://developer.arm.com/docs/dui0553/latest/the-cortex-m4-processor/memory-model/behavior-of-memory-accesses

**Comment by adamgreen** [comment] 2019-06-05 04:43
Ok. As a stopgap measure, I will look into adding a **--alias** command line option to CrashDebug to handle these type of situations. If this turns out to be a common requirement, we could think about adding an alias map feature to the CrashCatcher dumps themselves.

**Comment by adamgreen** [comment] 2019-06-05 04:45
```console
(gdb) info mem
Using memory regions provided by the target.
There are no memory regions defined.
```
I don't know what would cause that. You could log the data that goes between GDB and CrashDebug on startup and share the resulting log here. That way I can make sure that the memory description XML isn't corrupted somehow. The following flags added to the GDB command line will enable logging to test.log
``` console
 -ex "set remotelogfile test.log"
```

**Comment by swordligit** [comment] 2019-06-05 04:55
Maybe related with the data region and bss region, 
before added these two region, it is OK.
Following is log:
[test.log](https://github.com/adamgreen/CrashDebug/files/3255552/test.log)

**Comment by swordligit** [comment] 2019-06-05 05:28
The "info mem" result error because of bss region:
I print all the task's stack, which locate in the bss region,
and then I dump the whole bss region, there is some 
overlap, that my fool the gdb "info mem" command.
after I remove the task' stack region or bss region, it works correctly.
Thanks a lot.

**Comment by adamgreen** [comment] 2019-06-05 07:14
Ahh, I see what you mean by the overlap in that test.log  Nothing else looks out of line with that XML. Not truncated, corrupted, or anything else that CrashDebug obviously did wrong.

I will work on the alias feature later this week and let you know once I have something for you to try. I am changing the title of this issue to track the work item that resulted from tracking down the cause of the issue.

**Comment by swordligit** [comment] 2019-06-05 09:37
OK, you are so nice.
As for the alias, for our system, we have several section for alias,
sometimes for the CPU optimization, sometimes for setting different
 cache attributes. I am not sure the configuration file or command line 
arguments is the better way to define alias.
I will test the patch if they are ready, and if you need test files(elf, binary...),
please let me know.
Thanks a lot.

**Comment by swordligit** [comment] 2019-06-14 10:34
Hi, Adamgreen
     Is there any update about this issue now?

**Comment by adamgreen** [comment] 2019-06-14 17:31
Sorry, I have started working on this issue and issue #3 but higher priority tasks have kept preempting it over the last week. It is still high on my list and I hope to complete it next week.

**Comment by adamgreen** [comment] 2019-06-20 07:54
I have been working on this issue and #3 as well this week.

**Comment by swordligit** [comment] 2019-06-20 10:58
Great！waiting for you work finishing， if you need test, I will try.

**Comment by adamgreen** [comment] 2019-06-23 07:03
@swordligit 
I have just pushed up an update to the addAliasSupport branch which adds --alias support.

In your case, I think you would need to add these alias options to the end of your CrashDebug command line:
```console
--alias 0x3c000000 size_of_flash 0x0c000000 --alias 0x20000000 size_of_ram 0x200000
```

Currently the second parameter after the --alias option is the size of the alias region which can't exceed the size of the region it is redirecting to. This means you will need to tell it how large the flash (and ram) regions that you are loading into CrashDebug. I don't do this automatically based on what an address is being redirected to because I don't know that you don't have multiple alias redirects to different sub-regions of the same flash or ram region. If this ends up being an issue, I can have it clamp automatically to the maximum possible so that you can give the maximum size of the FLASH region (for example) and it will clamp the alias region down to what has actually been loaded from .elf or .bin.

Are you able to build CrashDebug for yourself? If not, which platform (Windows, macOS, Ubuntu) are you using?

**Comment by adamgreen** [comment] 2019-06-23 07:17
**PS:** I have added that size clamping functionality. On the command line, you can now just specify the overall size of the FLASH and RAM on your device and they will automatically be made smaller for the alias region if the redirect regions populated from .elf, .bin. and dumps turn out to be smaller.

**Comment by swordligit** [comment] 2019-06-24 06:49
Great！

> Are you able to build CrashDebug for yourself? If not, which platform (Windows, macOS, Ubuntu) are you using?

I cannot build, my platform is ubuntu1804, when building give me follow errors:
```
~/misc-projects/CrashDebug$ make CrashDebug
Compiling main/main.c
cc1: fatal error: mri/CppUTest/include/CppUTest/MemoryLeakDetectorMallocMacros.h: No such file or directory
compilation terminated.
makefile:259: recipe for target 'obj/main/main.o' failed
make: *** [obj/main/main.o] Error 1
```
or
```
~/misc-projects/CrashDebug$ make gcov
Building CPPUTEST_tests
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/Scrt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
makefile:191: recipe for target 'CPPUTEST_tests' failed
make: *** [CPPUTEST_tests] Error 1
```
my gcc version:
```
gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.4.0-1ubuntu1~18.04.1' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)
```

**Comment by adamgreen** [comment] 2019-06-24 07:11
It looks like you are missing the git submodules. The main README for this project does indicate [how to clone](https://github.com/adamgreen/CrashDebug#how-to-clone) and get those submodules.

**Comment by swordligit** [comment] 2019-06-24 08:05
Now it can build, but there is still errors, the gcc version is showed above.
```
libCrashDebug/src/MemorySim.c: In function ‘MemorySim_CreateAlias’:
libCrashDebug/src/MemorySim.c:209:104: error: argument ‘size’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Werror=clobbered]
 teAlias(IMemory* pMemory, uint32_t aliasAddress, uint32_t redirectAddress, uint32_t size)
                                                                                     ^~~~
cc1: all warnings being treated as errors
makefile:259: recipe for target 'obj/libCrashDebug/src/MemorySim.o' failed
make: *** [obj/libCrashDebug/src/MemorySim.o] Error 1
```

**Comment by adamgreen** [comment] 2019-06-24 20:54
Thanks for reporting the warning. I have updated the branch with a fix for this warning.

**Closed** 2019-06-25 00:46 UTC
