### ISSUE TITLE
Backtrace not working and cannot access flash memory

### ISSUE THREAD

**Issue by Gagnon06** [adamgreen/CrashDebug#4] opened 2018-12-14 18:43 UTC
Hi,
I am currently trying to use CrashCatcher and CrashDebug to help debugging HardFault on a Cortex M4 microcontroller. I successfully used CrashCatcher with a UART to dump the RAM and registers to a file on a PC when a HardFault happen (in my case a divide by zero). When I use CrashDebug with GDB, I am able to recover the line where the divide by zero happened, but I can't seem to get the full callstack. Using backtrace in GDB I have the following error :
`Backtrace stopped: previous frame identical to this frame (corrupt stack?)`

I tried debugging with GDB directly on a live MCU with a breakpoint in the HardFault handler and this way I can get the full callstack.

Another issue I have that may be related, is that GDB is unable to access memory in the flash section (which I assume is suppose to be read from the elf file). For example, I can't use the disas command in GDB without having this error :
`Cannot access memory at address 0x800fa44`

Have you encountered such an issue before?

Regards,
Leonard

**Comment by adamgreen** [comment] 2018-12-14 21:09
@Gagnon06 Would you be able to email your dump and corresponding .elf so that I can debug this issue? Something doesn't seem quite right here but I can't tell if the dump is missing something, the .elf didn't load successfully, or something else has gone amiss.

**Comment by Gagnon06** [comment] 2018-12-17 16:24
@adamgreen Thanks for the quick reply. I just sent you an email.

**Comment by adamgreen** [comment] 2018-12-17 20:33
Thanks!

My investigation so far:
* I started by asking GDB to show me the memory regions being exposed by CrashDebug.
```console
(gdb) info mem
Using memory regions provided by the target.
Num Enb Low Addr   High Addr  Attrs 
0   y  	0x0800dd94 0x0800de28 flash blocksize 0x1 nocache 
1   y  	0x20000000 0x20050000 rw nocache 
2   y  	0xe000ed28 0xe000ed3c rw nocache 
```

The first thing I notice is that the `flash` region is pretty small and it doesn't start at a nice aligned address. This is probably just the `.data` section and the `.text` session with the code is likely missing.

* Dumping the program header in the .ELF shows the following:
```console
~/Downloads/CrashDebug_debug$ arm-none-eabi-objdump -p stm32.elf 

stm32.elf:     file format elf32-littlearm

Program Header:
    LOAD off    0x00010000 vaddr 0x08000000 paddr 0x08000000 align 2**16
         filesz 0x0000dd94 memsz 0x0000dd94 flags rwx
    LOAD off    0x00020000 vaddr 0x20000000 paddr 0x0800dd94 align 2**16
         filesz 0x00000094 memsz 0x00000094 flags rw-
    LOAD off    0x00020098 vaddr 0x20000098 paddr 0x20000098 align 2**16
         filesz 0x00000000 memsz 0x000008ec flags rw-
private flags = 5000200: [Version5 EABI] [soft-float ABI]
```

The `.text` section appears to be marked as **W**riteable which causes CrashDebug to not load it since it figures that means it isn't FLASH. It does load the next section since `vaddr` and `paddr` don't match which means that it is likely the location of the initial contents of the `.data` section which are copied into RAM by the C runtime startup.

**Comment by adamgreen** [comment] 2018-12-18 02:37
@Gagnon06 I will modify CrashDebug to ignore the flags so that it will work with your binaries. I should have the fixed version posted soon.

Thanks for emailing me the information I needed to track down the cause of this issue.

**Closed** 2018-12-18 06:08 UTC

**Comment by adamgreen** [comment] 2018-12-18 06:53
Should be fixed now.

**Comment by Gagnon06** [comment] 2018-12-18 14:11
@adamgreen Thanks a lot for this fix. It works perfectly now. Great tool by the way!

**Comment by adamgreen** [comment] 2018-12-19 07:55
Excellent! Thanks for reporting!
